version: "3"
services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - 9000:9000
    networks:
      - jenkins
  jenkins:
    image: jenkins-docker:latest
    ports:
      - 8080:8080
    networks:
      - jenkins
networks:
  jenkins:
